[package]
name = "log-collector"
version.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
keywords.workspace = true
categories.workspace = true

[[bin]]
name = "log-collector"
path = "src/main.rs"

[dependencies]
candle-core = { path = "../candle-core" }
serde_json.workspace = true
clap.workspace = true
